### ISSUE TITLE
make iojs compatible

### ISSUE THREAD

**Issue by Dexus** [strongloop-forks/strong-fork-syslog#6]
see title

**Comment by rmg** [comment]
@Dexus we've recently switched our modules over to [modern-syslog](https://github.com/strongloop/modern-syslog), which @sam-github wrote as a drop-in replacement for node-syslog and strong-fork-syslog.

It should make its way out in a release of strongloop soon if that is how you are using it.

If you are trying to use it directly, you should be able to install and use modern-syslog right now
